
services:
  ubuntu_container:
    build: .
    container_name: usrp
    stdin_open: true
    tty: true

    volumes:
      - ../../masters/:/home/usrp/masters

    network_mode: "host"
    user: usrp